#!/usr/bin/env python3
"""Replace /** TODO: add documentation. */ stubs in Kotlin files with real
KDoc comments generated by the OpenAI Chat API.

Usage:
    OPENAI_API_KEY=sk-... python3 generate_kdoc.py [file.kt ...]

The script reads OPENAI_API_KEY from the environment. It processes each
supplied file, finds every stub, extracts the surrounding declaration context,
asks OpenAI to write proper KDoc, and writes the result back to the file.
"""

import os
import re
import sys

try:
    from openai import OpenAI
except ImportError:
    print(
        "ERROR: 'openai' package not found. Install it with: pip install openai",
        file=sys.stderr,
    )
    sys.exit(1)

STUB = "/** TODO: add documentation. */"

# Number of lines of body to include after the declaration for context.
# 15 lines is enough to cover parameters, return type, and the opening body
# of most short functions while keeping the token count (and API cost) low.
CONTEXT_BODY_LINES = 15

# Maximum tokens allowed for the generated KDoc response.
# 300 tokens is sufficient for a well-structured KDoc with a few @param /
# @return tags, while preventing runaway responses that inflate API costs.
MAX_KDOC_TOKENS = 300

SYSTEM_PROMPT = (
    "You are a Kotlin documentation expert. "
    "Given a Kotlin declaration and its surrounding code, write a concise KDoc comment for it. "
    "Include @param, @return, and @throws tags only when they add meaningful information. "
    "Do NOT include @constructor unless the class has notable constructor behaviour. "
    "Output ONLY the KDoc block (starting with /** and ending with */). "
    "Do not include any surrounding code, markdown fences, or extra explanation."
)


def _extract_context(lines: list, stub_idx: int, max_body_lines: int = CONTEXT_BODY_LINES) -> str:
    """Return a snippet of code following the stub (the declaration + body)."""
    # Skip the stub line itself and collect up to max_body_lines meaningful lines.
    snippet_lines = []
    for line in lines[stub_idx + 1 :]:
        snippet_lines.append(line.rstrip())
        if len(snippet_lines) >= max_body_lines:
            break
    return "\n".join(snippet_lines)


def _ask_openai(client: "OpenAI", context: str) -> str:
    """Call the OpenAI Chat API and return the generated KDoc string."""
    user_message = (
        "Write a KDoc comment for the following Kotlin declaration:\n\n"
        f"```kotlin\n{context}\n```"
    )
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.2,
        max_tokens=MAX_KDOC_TOKENS,
    )
    return response.choices[0].message.content.strip()


def _format_kdoc(raw: str, indent: str) -> str:
    """Ensure the KDoc returned by the model is properly indented and formatted."""
    # Strip any accidental markdown fences the model might include.
    raw = re.sub(r"^```[a-z]*\n?", "", raw.strip())
    raw = re.sub(r"\n?```$", "", raw.strip())
    raw = raw.strip()

    # If the model returned a single-line comment, keep it single-line.
    if "\n" not in raw:
        return f"{indent}{raw}\n"

    # Re-indent every line of a multi-line KDoc.
    result_lines = []
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped == "/**":
            result_lines.append(f"{indent}/**\n")
        elif stripped == "*/":
            result_lines.append(f"{indent} */\n")
        elif stripped.startswith("* ") or stripped == "*":
            result_lines.append(f"{indent} {stripped}\n")
        else:
            result_lines.append(f"{indent} * {stripped}\n")
    return "".join(result_lines)


def process_file(path: str, client: "OpenAI") -> bool:
    """Replace all TODO stubs in *path* with generated KDoc.
    Returns True if the file was modified."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()

    changed = False
    i = 0
    out = []

    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip()

        if stripped.lstrip() == STUB:
            indent = line[: len(line) - len(line.lstrip())]
            context = _extract_context(lines, i)

            if not context.strip():
                # No context to send — keep the stub as-is.
                out.append(line)
                i += 1
                continue

            try:
                raw_kdoc = _ask_openai(client, context)
                formatted = _format_kdoc(raw_kdoc, indent)
                out.append(formatted)
                changed = True
                print(f"  Generated KDoc at line {i + 1} in {path}")
            except Exception as exc:
                print(
                    f"  WARNING: OpenAI call failed for {path}:{i + 1} — {exc}",
                    file=sys.stderr,
                )
                out.append(line)
        else:
            out.append(line)

        i += 1

    if changed:
        with open(path, "w", encoding="utf-8") as fh:
            fh.writelines(out)
        print(f"Updated: {path}")

    return changed


def main() -> None:
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        print(
            "ERROR: OPENAI_API_KEY environment variable is not set.",
            file=sys.stderr,
        )
        sys.exit(1)

    client = OpenAI(api_key=api_key)

    errors = False
    for path in sys.argv[1:]:
        print(f"Processing: {path}")
        try:
            process_file(path, client)
        except Exception as exc:
            print(f"ERROR processing {path}: {exc}", file=sys.stderr)
            errors = True

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
